import { task } from "hardhat/config";
import type { TaskArguments } from "hardhat/types";
import * as fs from "fs";
import * as path from "path";

function asConstAbi(abi: unknown): string {
  return JSON.stringify(abi, null, 2);
}

task("sync-frontend", "Sync Sepolia deployment ABIs/addresses into frontend/src/config/contracts.ts")
  .addOptionalParam("networkName", "Hardhat-deploy network folder name", "sepolia")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const networkName: string = taskArguments.networkName ?? "sepolia";

    const deploymentsDir = path.join(hre.config.paths.root, "deployments", networkName);
    if (!fs.existsSync(deploymentsDir)) {
      throw new Error(`Missing deployments folder: ${deploymentsDir}. Deploy first with '--network ${networkName}'.`);
    }

    const predict = await hre.deployments.get("ObliviousPredict");
    const coin = await hre.deployments.get("ObliviousCoin");

    const outPath = path.join(hre.config.paths.root, "frontend", "src", "config", "contracts.ts");
    const out = `/* This file is auto-generated by 'npx hardhat sync-frontend --network sepolia'. */
export const SEPOLIA_CHAIN_ID = 11155111 as const;

export const OBLIVIOUS_PREDICT_ADDRESS = ${JSON.stringify(predict.address)} as const;
export const OBLIVIOUS_COIN_ADDRESS = ${JSON.stringify(coin.address)} as const;

export const OBLIVIOUS_PREDICT_ABI = ${asConstAbi(predict.abi)} as const;
export const OBLIVIOUS_COIN_ABI = ${asConstAbi(coin.abi)} as const;
`;

    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, out, { encoding: "utf8" });

    console.log(`Synced contracts to ${outPath}`);
    console.log(`ObliviousPredict: ${predict.address}`);
    console.log(`ObliviousCoin: ${coin.address}`);
  });

